database/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('web_v.urls', 'web_v'), namespace='webpages')),
]

web_v/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('classification/', views.classification, name='classification'),
    path('classification/community/', views.community, name='community'),
    path('classification/for_sale/', views.for_sale, name='for_sale'),
    path('classification/studying/', views.studying, name='studying'),
    path('classification/school/', views.school, name='school'),
    #失物招领
    path('classification/community/lost_find/', views.L_F, name='lost_find'),
    path('classification/community/lost_find/<int:L_F_T_id>/', views.L_F_T, name='lost_find_topic'),
    path('classification/community/lost_find/new_topic/', views.LFT_new_topic, name='LFT_new_topic'),
    path('classification/community/lost_find/new_entry/<int:L_F_T_id>/', views.LFT_new_entry, name='LFT_new_entry'),
    path('classification/community/lost_find_edit_entry/<int:L_F_E_id>/', views.LFT_edit_entry, name='LFT_edit_entry'),
    #电子产品
    path('classification/for_sale/electronics/', views.electronics, name='electronics'),
    path('classification/for_sale/electronics/<int:E_T_id>/', views.E_T, name='electronics_topic'),
    path('classification/for_sale/electronics/new_topic/', views.ET_new_topic, name='ET_new_topic'),
    path('classification/for_sale/electronics/new_entry/<int:E_T_id>/', views.ET_new_entry, name='ET_new_entry'),
    path('classification/for_sale/electronics/edit_entry/<int:E_E_id>/', views.ET_edit_entry, name='ET_edit_entry'),
    #日常用品
    path('classification/for_sale/necessary/',views.necessary, name='necessary'),
    path('classification/for_sale/necessary/<int:N_T_id>/', views.N_T, name='necessary_topic'),
    path('classification/for_sale/necessary/new_topic/', views.NT_new_topic, name='NT_new_topic'),
    path('classification/for_sale/nacessary/new_entry/<int:N_T_id>/', views.NT_new_entry, name='NT_new_entry'),
    path('classification/for_sale/necessary/edit_entry/<int:N_E_id>/', views.NT_edit_entry, name='NT_edit_entry'),
    

    
]

web_v/models.py
from django.db import models

# Create your models here.

class lost_find_topic(models.Model):
    text = models.CharField(max_length=300)
    L_F_T_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class lost_find_entry(models.Model):
    L_F_T = models.ForeignKey(lost_find_topic, on_delete=models.CASCADE)
    text = models.TextField()
    L_F_T_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Lost_find_topic_entries'

    def __str__(self):
        return self.text[:50] + "..."

class electronics_topic(models.Model):
    text = models.CharField(max_length=300)
    E_T_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class electronics_entry(models.Model):
    E_T = models.ForeignKey(electronics_topic, on_delete=models.CASCADE)
    text = models.TextField()
    E_T_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Electronics_topic_entries'

    def __str__(self):
        return self.text[:50] + "..."

class necessary_topic(models.Model):
    text = models.CharField(max_length=300)
    N_T_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class necessary_entry(models.Model):
    N_T = models.ForeignKey(necessary_topic, on_delete=models.CASCADE)
    text = models.TextField()
    N_T_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Necessary_topic_entries'

    def __str__(self):
        return self.text[:50] + "..."

web_v/forms.py
from django import forms
from .models import lost_find_topic
from .models import lost_find_entry
from .models import electronics_topic
from .models import electronics_entry
from .models import necessary_topic
from .models import necessary_entry

#失物招领
class LFT_Form(forms.ModelForm):
    class Meta:
        model = lost_find_topic
        fields = ['text']
        labels = {'text': ''}

class LFT_EntryForm(forms.ModelForm):
    class Meta:
        model = lost_find_entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

#电子产品
class ET_Form(forms.ModelForm):
    class Meta:
        model = electronics_topic
        fields = ['text']
        labels = {'text': ''}

class ET_EntryForm(forms.ModelForm):
    class Meta:
        model = electronics_entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

#日常用品
class NT_Form(forms.ModelForm):
    class Meta:
        model = necessary_topic
        fields = ['text']
        labels = {'text': ''}

class NT_EntryForm(forms.ModelForm):
    class Meta:
        model = necessary_entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

web_v/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import lost_find_topic
from .models import lost_find_entry
from .models import electronics_topic
from .models import electronics_entry
from .models import necessary_topic
from .models import necessary_entry
from .forms import LFT_Form
from .forms import LFT_EntryForm
from .forms import ET_Form
from .forms import ET_EntryForm
from .forms import NT_Form
from .forms import NT_EntryForm


# Create your views here.

def index(request):
    return render(request, 'webpages/index.html')

def topics(request):
    topics = Topic.objects.order_by('date')
    context = {'topics': topics}
    return render(request, 'webpages/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('date')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'webpages/topic.html', context)

def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id) 

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('webpages:topic',\
                                                args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'webpages/new_entry.html', context)

def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:topic',\
                                                args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'webpages/edit_entry.html', context)

def classification(request):
    return render(request, 'webpages/classification.html')

def for_sale(request):
    return render(request, 'webpages/for_sale/for_sale.html')

def community(request):
    return render(request, 'webpages/community/community.html')

def studying(request):
    return render(request, 'webpages/studying/studying.html')

def school(request):
    return render(request, 'webpages/school/school.html')

#community
    #失物招领
def L_F(request):
    L_F = lost_find_topic.objects.order_by('L_F_T_date')
    context = {'L_F': L_F}
    return render(request, 'webpages/community/lost_find.html', context)
    
def L_F_T(request, L_F_T_id):
    L_F_T = lost_find_topic.objects.get(id=L_F_T_id)
    L_F_T_entries = L_F_T.lost_find_entry_set.order_by('L_F_T_date')
    context = {'L_F_T':L_F_T, 'L_F_T_entries':L_F_T_entries}
    return render(request, 'webpages/community/lost_find_topic.html', context)

def LFT_new_topic(request):
    if request.method != 'POST':
        form = LFT_Form()
    else:
        form = LFT_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:lost_find'))
    context = {'form':form}
    return render(request, 'webpages/community/LFT_new_topic.html', context)

def LFT_new_entry(request, L_F_T_id):
    L_F_T = lost_find_topic.objects.get(id=L_F_T_id) 

    if request.method != 'POST':
        form = LFT_EntryForm()
    else:
        form = LFT_EntryForm(data=request.POST)
        if form.is_valid():
            LFT_new_entry = form.save(commit=False)
            LFT_new_entry.L_F_T = L_F_T
            LFT_new_entry.save()
            return HttpResponseRedirect(reverse('webpages:lost_find_topic',\
                                                args=[L_F_T_id]))
    context = {'L_F_T': L_F_T, 'form': form}
    return render(request, 'webpages/community/LFT_new_entry.html', context)

def LFT_edit_entry(request, L_F_E_id):
    L_F_E = lost_find_entry.objects.get(id=L_F_E_id)
    L_F_T = L_F_E.L_F_T
    if request.method != 'POST':
        form = LFT_EntryForm(instance=L_F_E)
    else:
        form = LFT_EntryForm(instance=L_F_E, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:lost_find_topic',\
                                                args=[L_F_T.id]))
    context = {'L_F_E': L_F_E, 'L_F_T': L_F_T, 'form': form}
    return render(request, 'webpages/community/LFT_edit_entry.html', context)

#for sale
    #电子产品
def electronics(request):
    electronics = electronics_topic.objects.order_by('E_T_date')
    context = {'electronics':electronics}
    return render(request, 'webpages/for_sale/electronics.html', context)

def E_T(request, E_T_id):
    E_T = electronics_topic.objects.get(id=E_T_id)
    E_T_entries = E_T.electronics_entry_set.order_by('E_T_date')
    context = {'E_T':E_T, 'E_T_entries':E_T_entries}
    return render(request, 'webpages/for_sale/electronics_topic.html', context)

def ET_new_topic(request):
    if request.method != 'POST':
        form = ET_Form()
    else:
        form = ET_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:electronics'))
    context = {'form':form}
    return render(request, 'webpages/for_sale/ET_new_topic.html', context)

def ET_new_entry(request, E_T_id):
    E_T = electronics_topic.objects.get(id=E_T_id)

    if request.method != 'POST':
        form = ET_EntryForm()
    else:
        form = ET_EntryForm(data=request.POST)
        if form.is_valid():
            ET_new_entry = form.save(commit=False)
            ET_new_entry.E_T = E_T
            ET_new_entry.save()
            return HttpResponseRedirect(reverse('webpages:electronics_topic',\
                                                args=[E_T_id]))
    context = {'E_T': E_T, 'form': form}
    return render(request, 'webpages/for_sale/ET_new_entry.html', context)

def ET_edit_entry(request, E_E_id):
    E_E = electronics_entry.objects.get(id=E_E_id)
    E_T = E_E.E_T
    if request.method != 'POST':
        form = ET_EntryForm(instance=E_E)
    else:
        form = ET_EntryForm(instance=E_E, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:electronics_topic',\
                                                args=[E_T.id]))
    context = {'E_E': E_E, 'E_T': E_T, 'form': form}
    return render(request, 'webpages/for_sale/ET_edit_entry.html', context)

    #日常用品
def necessary(request):
    necessary = necessary_topic.objects.order_by('N_T_date')
    context = {'necessary':necessary}
    return render(request, 'webpages/for_sale/necessary.html', context)

def N_T(request, N_T_id):
    N_T = necessary_topic.objects.get(id=N_T_id)
    N_T_entries = N_T.necessary_entry_set.order_by('N_T_date')
    context = {'N_T':N_T, 'N_T_entries':N_T_entries}
    return render(request, 'webpages/for_sale/necessary_topic.html', context)

def NT_new_topic(request):
    if request.method != 'POST':
        form = NT_Form()
    else:
        form = NT_Form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:necessary'))
    context = {'form':form}
    return render(request, 'webpages/for_sale/NT_new_topic.html', context)

def NT_new_entry(request, N_T_id):
    N_T = necessary_topic.objects.get(id=N_T_id) 

    if request.method != 'POST':
        form = NT_EntryForm()
    else:
        form = NT_EntryForm(data=request.POST)
        if form.is_valid():
            NT_new_entry = form.save(commit=False)
            NT_new_entry.N_T = N_T
            NT_new_entry.save()
            return HttpResponseRedirect(reverse('webpages:necessary_topic',\
                                                args=[N_T_id]))
    context = {'N_T': N_T, 'form': form}
    return render(request, 'webpages/for_sale/NT_new_entry.html', context)

def NT_edit_entry(request, N_E_id):
    N_E = necessary_entry.objects.get(id=N_E_id)
    N_T = N_E.N_T
    if request.method != 'POST':
        form = NT_EntryForm(instance=N_E)
    else:
        form = NT_EntryForm(instance=N_E, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webpages:necessary_topic',\
                                                args=[N_T.id]))
    context = {'N_E': N_E, 'N_T': N_T, 'form': form}
    return render(request, 'webpages/for_sale/NT_edit_entry.html', context)

web_v/templates/webpages/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="zh">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title></title>
		<link rel="stylesheet" type="text/css" href="/static/style/homepage.css/">
		<link rel="stylesheet" type="text/css" href="/static/style/searchlabel.css/">
		{% bootstrap_css %}
	</head>
	<body>
			<nav class="navbar navbar-expand-md navbar-light">
			<a class="navbar-brand" href="{% url 'webpages:index' %}">首页</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" 
			  data-target="#navbarCollapse" aria-controls="navbarCollapse" 
			  aria-expanded="false" aria-label="Toggle navigation" >
			  <span class="navbar-toggler-icon"></span></button>
				<dic class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'webpages:classification' %}">分类</a></li>
					</ul>
					<ul class="navbar-nav mr-auto">
        				<input type="text" class="search" placeholder="搜索">
        			</ul>
				</dic>
			</nav>
		<main role="main">
				{% block content %}{% endblock content %}
				<div class="footer">
  					<p>底部区域</p>
				</div>
		</main>
	</body>
</html>

web_v/templates/webpages/classification.html
{% extends "webpages/base.html" %}

{% block content %}
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="../../../static/style/classification.css">

	</head>
	<body>
		<div class="header">
			<h1>welcome</h1>
		</div>
		<div class="row no-gutters">
			<div class="column2 side2">
	
			</div>
			<div class="column2 middle2">
				<div class="title-line">
					<span class="tit" style="font-size: 35px;">分类</span>
				</div>
			</div>
		</div>

		<div class="row no-gutters">
			<div class="T_col">
				<div class="Topics">
					<div class="Topic">
						<div class="title" onclick="window.location.href= 'community/';return false">
							<span style="margin: 0 auto;">社区</span>
						</div>
						<div class="title-border"></div>
						<div class="topics">
							<div class="topic" onclick="window.location.href= 'community/lost_find/';return false">
								<span>失物招领</span>
							</div>
							<div class="topic">
								<span>论坛</span>
							</div>
							<div class="topic">
								<span>a</span>
							</div>
							<div class="topic">
								<span>b</span>
							</div>
							<div class="topic">
								<span>c</span>
							</div>
							<div class="topic">
								<span>d</span>
							</div>
							<div class="topic">
								<span>e</span>
							</div>
						</div>
					</div>
					<div class="Topic">
						<div class="title" onclick="window.location.href= 'for_sale/';return false">
							<span style="margin: 0 auto;">售卖</span>
						</div>
						<div class="title-border"></div>
						<div class="topics">
							<div class="topic" onclick="window.location.href='for_sale/electronics/';return false">
								<span>电子产品</span>
							</div>
							<div class="topic" onclick="window.location.href='for_sale/necessary/';return false">
								<span>日用品</span>
							</div>
						</div>
					</div>
					<div class="Topic">
						<div class="title" onclick="window.location.href= 'studying/';return false">
							<span style="margin: 0 auto;">学习</span>
						</div>
						<div class="title-border"></div>
					</div>
					<div class="Topic">
						<div class="title" onclick="window.location.href= 'school/';return false">
							<span style="margin: 0 auto;">学校</span>
						</div>
						<div class="title-border"></div>
					</div>
				</div>
			</div>
				<!-- -->
				<!-- -->

		</div>
	</body>
</html>

{% endblock content %}

web_v/templates/webpages/index.html
{% load bootstrap4 %}

{% block content %}
	
<!DOCTYPE>

<html>
	<head>
		<title>欢迎来到...</title>
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="../../../static/style/homepage.css">
		<link rel="stylesheet" type="text/css" href="../../../static/style/searchlabel.css">
		{% bootstrap_css %}

	</head>
	<body>
<div class="header">
	<nav class="navbar navbar-expand-md navbar-light">
		<a class="navbar-brand" href="{% url 'web_v:index' %}">首页</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" 
			  data-target="#navbarCollapse" aria-controls="navbarCollapse" 
			  aria-expanded="false" aria-label="Toggle navigation" >
		<span class="navbar-toggler-icon"></span></button>
			<dic class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'web_v:classification' %}">分类</a></li>
				</ul>
				<ul class="navbar-nav mr-auto">
        				<input type="text" class="search" placeholder="搜索">
        		</ul>
				/////
				////

				</dic>
			</nav>
</div>

<div class="row no-gutters">
  <div class="column side">
  </div>
  
  <div class="column middle">
    <h2>主区域内容</h2>
    <p>welcome</p>
  </div>
  
  <div class="column side">
  	
  </div>
</div>
<div class="footer">
  	<p>底部区域</p>
</div>
	</body>
</html>
{% endblock content %}